application: pixelbeat-comments-hrd
version: 1
runtime: python27
threadsafe: no
api_version: 1

handlers:

- url: /.*
  script: comments.py

#- url: /(comments\.py)
#  static_files: \1
#  upload: comments\.py
